name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          options: -v ./MyAppForLoadTest
          node-version: 18
      - name: Dependencies
        run: |
          npm ci
        working-directory: ./Playwright
        
      - name: Dependencies app
        run: |
          npm ci
        working-directory: ./MyAppForLoadTest
      - uses: actions/setup-node@v3
        with:
          options: -v ./Playwright
          node-version: 18
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
        working-directory: ./MyAppForLoadTest
      - name: Push Docker image
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
        working-directory: ./MyAppForLoadTest
          
      - name: Run the image in a container
        run : docker run -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
        working-directory: ./MyAppForLoadTest
          
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./Playwright
      - name: Run Playwright tests
        run: npx playwright test MetaUniverse.spec.js 
        working-directory: ./Playwright
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
