name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Dependencies
        run: |
          npm ci
        working-directory: ./Playwright
        
      - name: run docker image
        run: |
          cd ./MyAppForLoadTest
          docker build . -t express
      - name: run docker container 
        uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}:/app
          run: |
            docker run -p 3000:3000 express
          
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./Playwright
      - name: Run Playwright tests
        run: npx playwright test MetaUniverse.spec.js 
        working-directory: ./Playwright
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
